level_limit: 3
api_key: <%= ENV['API_KEY'] || 'QoUGgaASQMHMRB' %>
elasticsearch_server: <%= ENV['SEARCH_SERVER'] || 'http://localhost:9200' %>
max_deep_search_comment_count: 5000
default_locale: <%= ENV['SERVICE_LANGUAGE'] || 'en-US' %>
